"""Generate the ring-counting Cypher queries (queries/4f1-4f3, 4g).

Why generated: a quantified pattern like (a) (()-[:FLOWS_TO]->()){2,12} (a)
only keeps relationships unique, so Neo4j explores walks that revisit
accounts (a->b->a->b...) and filters them out only at the end. On this
graph that is billions of walks and exhausts the transaction memory pool.
Writing one fixed-length pattern per ring length lets the planner apply
"new account, same SCC, higher accountId than the start" at every hop,
which keeps the full 2..12 search to a few million expansions.

Usage: python gen_ring_queries.py [MAXLEN]   (default 12)
"""
import sys

MAXLEN = int(sys.argv[1]) if len(sys.argv) > 1 else 12

EXPECTED = {
    12: {"4f1": "12,885 rings / 2,086 laundering",
         "4f2": "4,224 rings / 219 laundering",
         "4f3": "1,234 rings / 80 laundering",
         "4g": "6,941 accounts"},
    8: {"4f1": "6,621 rings / 1,222 laundering",
        "4f2": "4,201 rings / 205 laundering",
        "4f3": "1,224 rings / 70 laundering",
        "4g": "6,845 accounts"},
}

HEADER = f"""// GENERATED by gen_ring_queries.py (ring lengths 2..{MAXLEN}) - edit the generator.
// Requires 4f0a (FLOWS_TO) and 4f0b-4f0d (sccId). Rings are sets of distinct
// accounts a -> ... -> a over FLOWS_TO, counted once from their lowest
// accountId. One fixed-length pattern per ring length so Neo4j can reject a
// repeated account at each hop (see gen_ring_queries.py for why)."""


def ring_branches():
    """UNION ALL of one MATCH per ring length, each returning ring and f."""
    branches = []
    for k in range(2, MAXLEN + 1):
        inner = [f"n{i}" for i in range(1, k)]
        hops = "(a)" + "".join(f"-[f{i}:FLOWS_TO]->({inner[i - 1]})" for i in range(1, k))
        hops += f"-[f{k}:FLOWS_TO]->(a)"
        conds = []
        for i, n in enumerate(inner):
            c = f"{n}.sccId = a.sccId AND {n}.accountId > a.accountId"
            if i > 0:
                c += f" AND NOT {n} IN [{', '.join(inner[:i])}]"
            conds.append(c)
        branches.append(
            f"  MATCH {hops}\n"
            f"  WHERE " + "\n    AND ".join(conds) + "\n"
            f"  RETURN [a, {', '.join(inner)}] AS ring, [{', '.join(f'f{i}' for i in range(1, k + 1))}] AS f"
        )
    return "\n  UNION ALL\n".join(branches)


RINGS = f"""MATCH (a:Account)
WHERE EXISTS {{ (a)-[:FLOWS_TO]->(b:Account) WHERE b.sccId = a.sccId }}
CALL (a) {{
{ring_branches()}
}}"""

ROTATIONS = "WITH ring, [k IN range(0, size(f)-1) | f[k..] + f[..k]] AS rotations"


def temporal_check(laundering_only):
    """True if some rotation admits a time-ordered choice of transactions."""
    lf0 = " WHERE rot[0].laund[j] = 1" if laundering_only else ""
    lf = "e.laund[j] = 1 AND " if laundering_only else ""
    return f"""any(rot IN rotations WHERE size(reduce(
         st = [j IN range(0, size(rot[0].ts)-1){lf0} | rot[0].ts[j]],
         e IN rot[1..] |
         [j IN range(0, size(e.ts)-1) WHERE {lf}any(t IN st WHERE e.ts[j] >= t)
          | e.ts[j]])) > 0)"""


def amount_check(laundering_only):
    """As temporal_check, plus each hop passes on 50-120% of the previous USD value."""
    lf0 = " WHERE rot[0].laund[j] = 1" if laundering_only else ""
    lf = "e.laund[j] = 1 AND " if laundering_only else ""
    return f"""any(rot IN rotations WHERE size(reduce(
         st = [j IN range(0, size(rot[0].ts)-1){lf0} | [rot[0].ts[j], rot[0].usd[j]]],
         e IN rot[1..] |
         [j IN range(0, size(e.ts)-1) WHERE {lf}any(s IN st WHERE e.ts[j] >= s[0]
            AND e.usd[j] > 0.5 * s[1] AND e.usd[j] < 1.2 * s[1])
          | [e.ts[j], e.usd[j]]])) > 0)"""


COUNT_RETURN = """RETURN count(*) AS rings,
       sum(CASE WHEN okLaundering THEN 1 ELSE 0 END) AS launderingRings"""


def expected(key):
    e = EXPECTED.get(MAXLEN)
    return f"// Expected ({{2,{MAXLEN}}}): {e[key]}." if e else "// Expected: not precomputed for this range."


QUERIES = {
    "4f1_count_basic.cypher": f"""// 4f (1/3). Count all rings (no temporal or amount filter).
// launderingRings = every hop has at least one laundering transaction.
{expected("4f1")}
{HEADER}
{RINGS}
RETURN count(*) AS rings,
       sum(CASE WHEN all(e IN f WHERE 1 IN e.laund) THEN 1 ELSE 0 END) AS launderingRings
""",
    "4f2_count_temporal.cypher": f"""// 4f (2/3). Count temporal rings: starting at some ring member, one real
// transaction per hop can be chosen so each is no earlier than the previous.
// Check (per rotation): st = timestamps reachable at the current hop; a hop
// keeps transactions no earlier than some reachable one; non-empty at the
// end = feasible. launderingRings = feasible using laundering txns only.
{expected("4f2")}
{HEADER}
{RINGS}
{ROTATIONS}
WITH {temporal_check(False)} AS ok,
     {temporal_check(True)} AS okLaundering
WHERE ok
{COUNT_RETURN}
""",
    "4f3_count_temporal_amount.cypher": f"""// 4f (3/3). Count temporal rings with amount conservation: as 4f2, and each
// chosen hop passes on 50-120% of the previous hop's USD value.
// States are [timestamp, usd] pairs of transactions reachable at each hop.
{expected("4f3")}
{HEADER}
{RINGS}
{ROTATIONS}
WITH {amount_check(False)} AS ok,
     {amount_check(True)} AS okLaundering
WHERE ok
{COUNT_RETURN}
""",
    "4g_mark_cycle_members.cypher": f"""// 4g. Mark members of temporal rings (as 4f2) with inCycle = true.
// UPDATE for CRUD; used by the risk score.
{expected("4g")}
{HEADER}
{RINGS}
{ROTATIONS}
WHERE {temporal_check(False)}
UNWIND ring AS n
WITH DISTINCT n
SET n.inCycle = true
RETURN count(n) AS accountsInCycles
""",
}

for name, text in QUERIES.items():
    with open(f"queries/{name}", "w", newline="\n") as fh:
        fh.write(text)
    print("wrote queries/" + name)
