// 4g. Mark members of temporal rings (as 4f2) with inCycle = true.
// UPDATE for CRUD; used by the risk score.
// Expected ({2,12}): 6,941 accounts.
// GENERATED by gen_ring_queries.py (ring lengths 2..12) - edit the generator.
// Requires 4f0a (FLOWS_TO) and 4f0b-4f0d (sccId). Rings are sets of distinct
// accounts a -> ... -> a over FLOWS_TO, counted once from their lowest
// accountId. One fixed-length pattern per ring length so Neo4j can reject a
// repeated account at each hop (see gen_ring_queries.py for why).
MATCH (a:Account)
WHERE EXISTS { (a)-[:FLOWS_TO]->(b:Account) WHERE b.sccId = a.sccId }
CALL (a) {
  MATCH (a)-[f1:FLOWS_TO]->(n1)-[f2:FLOWS_TO]->(a)
  WHERE n1.sccId = a.sccId AND n1.accountId > a.accountId
  RETURN [a, n1] AS ring, [f1, f2] AS f
  UNION ALL
  MATCH (a)-[f1:FLOWS_TO]->(n1)-[f2:FLOWS_TO]->(n2)-[f3:FLOWS_TO]->(a)
  WHERE n1.sccId = a.sccId AND n1.accountId > a.accountId
    AND n2.sccId = a.sccId AND n2.accountId > a.accountId AND NOT n2 IN [n1]
  RETURN [a, n1, n2] AS ring, [f1, f2, f3] AS f
  UNION ALL
  MATCH (a)-[f1:FLOWS_TO]->(n1)-[f2:FLOWS_TO]->(n2)-[f3:FLOWS_TO]->(n3)-[f4:FLOWS_TO]->(a)
  WHERE n1.sccId = a.sccId AND n1.accountId > a.accountId
    AND n2.sccId = a.sccId AND n2.accountId > a.accountId AND NOT n2 IN [n1]
    AND n3.sccId = a.sccId AND n3.accountId > a.accountId AND NOT n3 IN [n1, n2]
  RETURN [a, n1, n2, n3] AS ring, [f1, f2, f3, f4] AS f
  UNION ALL
  MATCH (a)-[f1:FLOWS_TO]->(n1)-[f2:FLOWS_TO]->(n2)-[f3:FLOWS_TO]->(n3)-[f4:FLOWS_TO]->(n4)-[f5:FLOWS_TO]->(a)
  WHERE n1.sccId = a.sccId AND n1.accountId > a.accountId
    AND n2.sccId = a.sccId AND n2.accountId > a.accountId AND NOT n2 IN [n1]
    AND n3.sccId = a.sccId AND n3.accountId > a.accountId AND NOT n3 IN [n1, n2]
    AND n4.sccId = a.sccId AND n4.accountId > a.accountId AND NOT n4 IN [n1, n2, n3]
  RETURN [a, n1, n2, n3, n4] AS ring, [f1, f2, f3, f4, f5] AS f
  UNION ALL
  MATCH (a)-[f1:FLOWS_TO]->(n1)-[f2:FLOWS_TO]->(n2)-[f3:FLOWS_TO]->(n3)-[f4:FLOWS_TO]->(n4)-[f5:FLOWS_TO]->(n5)-[f6:FLOWS_TO]->(a)
  WHERE n1.sccId = a.sccId AND n1.accountId > a.accountId
    AND n2.sccId = a.sccId AND n2.accountId > a.accountId AND NOT n2 IN [n1]
    AND n3.sccId = a.sccId AND n3.accountId > a.accountId AND NOT n3 IN [n1, n2]
    AND n4.sccId = a.sccId AND n4.accountId > a.accountId AND NOT n4 IN [n1, n2, n3]
    AND n5.sccId = a.sccId AND n5.accountId > a.accountId AND NOT n5 IN [n1, n2, n3, n4]
  RETURN [a, n1, n2, n3, n4, n5] AS ring, [f1, f2, f3, f4, f5, f6] AS f
  UNION ALL
  MATCH (a)-[f1:FLOWS_TO]->(n1)-[f2:FLOWS_TO]->(n2)-[f3:FLOWS_TO]->(n3)-[f4:FLOWS_TO]->(n4)-[f5:FLOWS_TO]->(n5)-[f6:FLOWS_TO]->(n6)-[f7:FLOWS_TO]->(a)
  WHERE n1.sccId = a.sccId AND n1.accountId > a.accountId
    AND n2.sccId = a.sccId AND n2.accountId > a.accountId AND NOT n2 IN [n1]
    AND n3.sccId = a.sccId AND n3.accountId > a.accountId AND NOT n3 IN [n1, n2]
    AND n4.sccId = a.sccId AND n4.accountId > a.accountId AND NOT n4 IN [n1, n2, n3]
    AND n5.sccId = a.sccId AND n5.accountId > a.accountId AND NOT n5 IN [n1, n2, n3, n4]
    AND n6.sccId = a.sccId AND n6.accountId > a.accountId AND NOT n6 IN [n1, n2, n3, n4, n5]
  RETURN [a, n1, n2, n3, n4, n5, n6] AS ring, [f1, f2, f3, f4, f5, f6, f7] AS f
  UNION ALL
  MATCH (a)-[f1:FLOWS_TO]->(n1)-[f2:FLOWS_TO]->(n2)-[f3:FLOWS_TO]->(n3)-[f4:FLOWS_TO]->(n4)-[f5:FLOWS_TO]->(n5)-[f6:FLOWS_TO]->(n6)-[f7:FLOWS_TO]->(n7)-[f8:FLOWS_TO]->(a)
  WHERE n1.sccId = a.sccId AND n1.accountId > a.accountId
    AND n2.sccId = a.sccId AND n2.accountId > a.accountId AND NOT n2 IN [n1]
    AND n3.sccId = a.sccId AND n3.accountId > a.accountId AND NOT n3 IN [n1, n2]
    AND n4.sccId = a.sccId AND n4.accountId > a.accountId AND NOT n4 IN [n1, n2, n3]
    AND n5.sccId = a.sccId AND n5.accountId > a.accountId AND NOT n5 IN [n1, n2, n3, n4]
    AND n6.sccId = a.sccId AND n6.accountId > a.accountId AND NOT n6 IN [n1, n2, n3, n4, n5]
    AND n7.sccId = a.sccId AND n7.accountId > a.accountId AND NOT n7 IN [n1, n2, n3, n4, n5, n6]
  RETURN [a, n1, n2, n3, n4, n5, n6, n7] AS ring, [f1, f2, f3, f4, f5, f6, f7, f8] AS f
  UNION ALL
  MATCH (a)-[f1:FLOWS_TO]->(n1)-[f2:FLOWS_TO]->(n2)-[f3:FLOWS_TO]->(n3)-[f4:FLOWS_TO]->(n4)-[f5:FLOWS_TO]->(n5)-[f6:FLOWS_TO]->(n6)-[f7:FLOWS_TO]->(n7)-[f8:FLOWS_TO]->(n8)-[f9:FLOWS_TO]->(a)
  WHERE n1.sccId = a.sccId AND n1.accountId > a.accountId
    AND n2.sccId = a.sccId AND n2.accountId > a.accountId AND NOT n2 IN [n1]
    AND n3.sccId = a.sccId AND n3.accountId > a.accountId AND NOT n3 IN [n1, n2]
    AND n4.sccId = a.sccId AND n4.accountId > a.accountId AND NOT n4 IN [n1, n2, n3]
    AND n5.sccId = a.sccId AND n5.accountId > a.accountId AND NOT n5 IN [n1, n2, n3, n4]
    AND n6.sccId = a.sccId AND n6.accountId > a.accountId AND NOT n6 IN [n1, n2, n3, n4, n5]
    AND n7.sccId = a.sccId AND n7.accountId > a.accountId AND NOT n7 IN [n1, n2, n3, n4, n5, n6]
    AND n8.sccId = a.sccId AND n8.accountId > a.accountId AND NOT n8 IN [n1, n2, n3, n4, n5, n6, n7]
  RETURN [a, n1, n2, n3, n4, n5, n6, n7, n8] AS ring, [f1, f2, f3, f4, f5, f6, f7, f8, f9] AS f
  UNION ALL
  MATCH (a)-[f1:FLOWS_TO]->(n1)-[f2:FLOWS_TO]->(n2)-[f3:FLOWS_TO]->(n3)-[f4:FLOWS_TO]->(n4)-[f5:FLOWS_TO]->(n5)-[f6:FLOWS_TO]->(n6)-[f7:FLOWS_TO]->(n7)-[f8:FLOWS_TO]->(n8)-[f9:FLOWS_TO]->(n9)-[f10:FLOWS_TO]->(a)
  WHERE n1.sccId = a.sccId AND n1.accountId > a.accountId
    AND n2.sccId = a.sccId AND n2.accountId > a.accountId AND NOT n2 IN [n1]
    AND n3.sccId = a.sccId AND n3.accountId > a.accountId AND NOT n3 IN [n1, n2]
    AND n4.sccId = a.sccId AND n4.accountId > a.accountId AND NOT n4 IN [n1, n2, n3]
    AND n5.sccId = a.sccId AND n5.accountId > a.accountId AND NOT n5 IN [n1, n2, n3, n4]
    AND n6.sccId = a.sccId AND n6.accountId > a.accountId AND NOT n6 IN [n1, n2, n3, n4, n5]
    AND n7.sccId = a.sccId AND n7.accountId > a.accountId AND NOT n7 IN [n1, n2, n3, n4, n5, n6]
    AND n8.sccId = a.sccId AND n8.accountId > a.accountId AND NOT n8 IN [n1, n2, n3, n4, n5, n6, n7]
    AND n9.sccId = a.sccId AND n9.accountId > a.accountId AND NOT n9 IN [n1, n2, n3, n4, n5, n6, n7, n8]
  RETURN [a, n1, n2, n3, n4, n5, n6, n7, n8, n9] AS ring, [f1, f2, f3, f4, f5, f6, f7, f8, f9, f10] AS f
  UNION ALL
  MATCH (a)-[f1:FLOWS_TO]->(n1)-[f2:FLOWS_TO]->(n2)-[f3:FLOWS_TO]->(n3)-[f4:FLOWS_TO]->(n4)-[f5:FLOWS_TO]->(n5)-[f6:FLOWS_TO]->(n6)-[f7:FLOWS_TO]->(n7)-[f8:FLOWS_TO]->(n8)-[f9:FLOWS_TO]->(n9)-[f10:FLOWS_TO]->(n10)-[f11:FLOWS_TO]->(a)
  WHERE n1.sccId = a.sccId AND n1.accountId > a.accountId
    AND n2.sccId = a.sccId AND n2.accountId > a.accountId AND NOT n2 IN [n1]
    AND n3.sccId = a.sccId AND n3.accountId > a.accountId AND NOT n3 IN [n1, n2]
    AND n4.sccId = a.sccId AND n4.accountId > a.accountId AND NOT n4 IN [n1, n2, n3]
    AND n5.sccId = a.sccId AND n5.accountId > a.accountId AND NOT n5 IN [n1, n2, n3, n4]
    AND n6.sccId = a.sccId AND n6.accountId > a.accountId AND NOT n6 IN [n1, n2, n3, n4, n5]
    AND n7.sccId = a.sccId AND n7.accountId > a.accountId AND NOT n7 IN [n1, n2, n3, n4, n5, n6]
    AND n8.sccId = a.sccId AND n8.accountId > a.accountId AND NOT n8 IN [n1, n2, n3, n4, n5, n6, n7]
    AND n9.sccId = a.sccId AND n9.accountId > a.accountId AND NOT n9 IN [n1, n2, n3, n4, n5, n6, n7, n8]
    AND n10.sccId = a.sccId AND n10.accountId > a.accountId AND NOT n10 IN [n1, n2, n3, n4, n5, n6, n7, n8, n9]
  RETURN [a, n1, n2, n3, n4, n5, n6, n7, n8, n9, n10] AS ring, [f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11] AS f
  UNION ALL
  MATCH (a)-[f1:FLOWS_TO]->(n1)-[f2:FLOWS_TO]->(n2)-[f3:FLOWS_TO]->(n3)-[f4:FLOWS_TO]->(n4)-[f5:FLOWS_TO]->(n5)-[f6:FLOWS_TO]->(n6)-[f7:FLOWS_TO]->(n7)-[f8:FLOWS_TO]->(n8)-[f9:FLOWS_TO]->(n9)-[f10:FLOWS_TO]->(n10)-[f11:FLOWS_TO]->(n11)-[f12:FLOWS_TO]->(a)
  WHERE n1.sccId = a.sccId AND n1.accountId > a.accountId
    AND n2.sccId = a.sccId AND n2.accountId > a.accountId AND NOT n2 IN [n1]
    AND n3.sccId = a.sccId AND n3.accountId > a.accountId AND NOT n3 IN [n1, n2]
    AND n4.sccId = a.sccId AND n4.accountId > a.accountId AND NOT n4 IN [n1, n2, n3]
    AND n5.sccId = a.sccId AND n5.accountId > a.accountId AND NOT n5 IN [n1, n2, n3, n4]
    AND n6.sccId = a.sccId AND n6.accountId > a.accountId AND NOT n6 IN [n1, n2, n3, n4, n5]
    AND n7.sccId = a.sccId AND n7.accountId > a.accountId AND NOT n7 IN [n1, n2, n3, n4, n5, n6]
    AND n8.sccId = a.sccId AND n8.accountId > a.accountId AND NOT n8 IN [n1, n2, n3, n4, n5, n6, n7]
    AND n9.sccId = a.sccId AND n9.accountId > a.accountId AND NOT n9 IN [n1, n2, n3, n4, n5, n6, n7, n8]
    AND n10.sccId = a.sccId AND n10.accountId > a.accountId AND NOT n10 IN [n1, n2, n3, n4, n5, n6, n7, n8, n9]
    AND n11.sccId = a.sccId AND n11.accountId > a.accountId AND NOT n11 IN [n1, n2, n3, n4, n5, n6, n7, n8, n9, n10]
  RETURN [a, n1, n2, n3, n4, n5, n6, n7, n8, n9, n10, n11] AS ring, [f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12] AS f
}
WITH ring, [k IN range(0, size(f)-1) | f[k..] + f[..k]] AS rotations
WHERE any(rot IN rotations WHERE size(reduce(
         st = [j IN range(0, size(rot[0].ts)-1) | rot[0].ts[j]],
         e IN rot[1..] |
         [j IN range(0, size(e.ts)-1) WHERE any(t IN st WHERE e.ts[j] >= t)
          | e.ts[j]])) > 0)
UNWIND ring AS n
WITH DISTINCT n
SET n.inCycle = true
RETURN count(n) AS accountsInCycles
